default_context:
  project_name: 'ippf'
  project_slug: 'ippf'
  domain_main: 'ippf.com'
  domain_staging: 'stag.ippf.com'
  docker_swarm_stack_name_main: 'ippf-com'
  docker_swarm_stack_name_staging: 'stag-ippf-com'
  secret_key: '3f718fe6e9c878a37c16b419cf4967eee9039f6cd9ebf1eb9a6458d380a5b98f'
  first_superuser: 'admin@ippf.com'
  first_superuser_password: 'a0c85c31f5'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.ippf.com", "https://stag.ippf.com", "https://ippf.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@ippf.com'
  postgres_password: 'changethis'
  pgadmin_default_user: 'admin@ippf.com'
  pgadmin_default_user_password: 'a0c85c31f5'
  traefik_constraint_tag: 'ippf.com'
  traefik_constraint_tag_staging: 'stag.ippf.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:a0c85c31f5'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'ippfbackend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'ippffrontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
